- name: "Web user configs for env"
  become: no
  hosts: all
  gather_facts: false
  roles:
    - role: node
      vars:
        node_version: 18
      when: inventory_hostname == "app-crm" or inventory_hostname == "app-core"
    - role: node
      vars:
        node_version: 20
      when: inventory_hostname != "app-docker" and inventory_hostname != "app-crm" and inventory_hostname != "app-core"

  vars:
    repo_list:
      - { link: "", folder_name: "master", branch_name: "", host_name: "app-main" }
      - { link: "", folder_name: "master", branch_name: "", host_name: "app-crm" }
      - { link: "", folder_name: "master/backend", branch_name: "", host_name: "app-core" }
      - { link: "", folder_name: "master/frontend", branch_name: "", host_name: "app-core" }
      - { link: "", folder_name: "master", branch_name: "", host_name: "app-nko" }

  tasks:
    - name: "Install PM2"
      shell: |
        /bin/bash -c "source ~/.nvm/nvm.sh && npm install -g pm2"
      when: inventory_hostname != "app-docker"